name = 'letsworship-sync'
main = 'src/index.js'
compatibility_date = '2026-08-23'

[[durable_objects.bindings]]
name = 'ROOMS'
class_name = 'SyncRoom'

[[migrations]]
tag = 'v1'
new_sqlite_classes = ['SyncRoom']
